wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("search/", views.search, name="search"),
    path("wiki/<str:title>", views.entry, name="entry"),
    path("create/", views.create, name="create"),
    path("edit/", views.edit, name="edit"),
    path("save/", views.save, name="save"),
    path("random/", views.random_page, name="random")
]

wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/encyclopedia/views.py
from django.shortcuts import render
from django import forms
from markdown2 import Markdown
import random

from . import util



def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def convert_md_to_html(title):
    content = util.get_entry(title)
    markdowner = Markdown()
    if content == None:
        return None
    else:
        return markdowner.convert(content)

def search(request):
    if request.method == "POST":
        query = request.POST["q"] 
        html_content = convert_md_to_html(query)
        all_entries = util.list_entries() 
        similar_entries=[]   
        if html_content != None:   
            return render(request, "encyclopedia/entries.html", {
                "content" : html_content ,
                "title": query
            })
        else:
            for entry in all_entries:
                if query.lower() in entry.lower():
                    similar_entries.append(entry)

            if similar_entries:
                return render(request, "encyclopedia/similar_entries.html", {
                    "similar_entries" : similar_entries
                })    

            else:
                return render(request, "encyclopedia/error.html", {
                    "message": "No pages match your search."
                })    



def create(request):
    if request.method == "POST":
        name=request.POST["name"]
        content = request.POST["description"]
        title = util.get_entry(name)
        if not name:
            return render(request, "encyclopedia/error.html", {
                    "message": "Should provide name of the article."
                }) 
        elif not content:
            return render(request, "encyclopedia/error.html", {
                    "message": "Page cannot be empty."
                })
        elif title != None:
            return render(request, "encyclopedia/error.html", {
                    "message": "Page already exists."
                })
        
        else:   
            util.save_entry(name, content)
            content = convert_md_to_html(name)
            return render(request, "encyclopedia/success.html", {
                "content" : util.get_entry(name),
                "title": name
            })

    return render(request, "encyclopedia/create.html")

def entry(request, title):
    html_content = convert_md_to_html(title)

    if html_content == None:
        return render(request, "encyclopedia/error.html", {
            "message": "This page does not exist"
        })
    
    else:
        return render(request, "encyclopedia/entries.html", {
            "title": title,
            "content": html_content
        })

def edit(request):
    if request.method == "POST":
        title = request.POST["entry_title"]
        content = util.get_entry(title)
        return render(request, "encyclopedia/edit.html", {
            "title": title,
            "content": content
        })
    
def save(request):
    if request.method == "POST":
        title = request.POST["name"]
        content = request.POST["description"]
        util.save_entry(title, content)
        content = convert_md_to_html(title)
        return render(request, "encyclopedia/success.html", {
            "content" : util.get_entry(title),
            "title": title
        })
    
def random_page(request):
    all_entries=util.list_entries()
    guess = random.randrange(0, len(all_entries))
    title = all_entries[guess]
    content = util.get_entry(title)
    return render(request, "encyclopedia/entries.html", {
        "title":  title,
        "content": content
    })

wiki/encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Create Page
{% endblock %}

{% block body %}

    <h1 style="text-align: center">Create Page</h1>

    <div class="container">
        
        <form action="{% url 'encyclopedia:create' %}" method="post">
            {% csrf_token %}
            <div class="mb-3 mt-3">
              <label for="name" class="form-label"><b>Enter name of your Article:</b></label>
              <input type="text" class="form-control" id="name" placeholder="Article name" name="name">
            </div>
            <div class="mb-3">
                <label for="description"><b>Article description (Markdown content):</b></label>
                <textarea class="form-control" rows="5" id="description" name="description" placeholder="Write here...."></textarea>
            </div>
            
            <input type="submit" class="btn btn-primary" value="Submit">
        </form>
    </div>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Page
{% endblock %}

{% block body %}

    <h1 style="text-align: center">Edit Page</h1>

    <div class="container">
        
        <form action="{% url 'encyclopedia:save' %}" method="post">
            {% csrf_token %}
            <div class="mb-3 mt-3">
              <label for="name" class="form-label"><b>Enter name of your Article:</b></label>
              <input type="text" class="form-control" id="name" name="name" value="{{title}}">
            </div>
            <div class="mb-3">
                <label for="description"><b>Article description (Markdown content):</b></label>
                <textarea class="form-control" rows="5" id="description" name="description">{{content}}</textarea>
            </div>
            
            <input type="submit" class="btn btn-primary" value="Save">
        </form>
    </div>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/entries.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body%}
    <h1>    {{title}}</h1>
    <p>{{  content | safe }}</p>

    <form action="{% url 'encyclopedia:edit' %}"  method="post">
        {% csrf_token %}
        <input type="hidden" name="entry_title" value = "{{title}}">
        <input type="submit" class="btn btn-primary" value="Edit this page">
    </form>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Error
{% endblock %}

{% block body %}

    <h1>Error</h1>
    
    {{ message }}

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href = "{% url 'encyclopedia:entry' title=entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}"> Create New Page </a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page </a>
                    
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

wiki/encyclopedia/templates/encyclopedia/similar_entries.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Similar Pages</h1>

    <ul>
        {% for entry in similar_entries %}
            <li><a href = "{% url 'encyclopedia:entry' title=entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/encyclopedia/templates/encyclopedia/success.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{title}}
{% endblock %}

{% block body %}

    <h1 style="text-align: center"></h1>
    <div class="alert alert-success">
        <strong>Success!</strong>
      </div>
    <h1>{{title}}</h1>
    
    {{content}}

{% endblock %}